variables:
- template: /eng/common-variables.yml
- template: /eng/common/templates/variables/pool-providers.yml

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pr:
  branches:
    include:
    - main
    - release/*

# Build

stages:
- stage: Build_OSX
  displayName: Build OSX
  dependsOn:
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableTelemetry: true
      enablePublishBuildArtifacts: true
      enableMicrobuild: true
      publishingVersion: 4
      enablePublishBuildAssets: true
      helixRepo: dotnet/xharness

      jobs:
      - job: OSX
        enablePublishing: true
        pool:
          vmImage: macOS-15
        strategy:
          matrix:
            Release:
              _BuildConfig: Release
              _PublishArgs: ''
            Debug:
              _BuildConfig: Debug
              _PublishArgs: /p:Publish=false
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            $(_PublishArgs)
          name: Build
          displayName: Build and run tests
          condition: succeeded()

        - publish: $(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/Shipping/Microsoft.DotNet.XHarness.CLI.11.0.0-ci.nupkg
          artifact: Microsoft.DotNet.XHarness.CLI.$(_BuildConfig)
          displayName: Publish XHarness CLI for Helix Testing
          condition: and(succeeded(), eq(variables['_BuildConfig'], 'Debug'))

        - task: PublishTestResults@2
          displayName: 'Publish Unit Test Results'
          inputs:
            testResultsFormat: xUnit
            testResultsFiles: '$(Build.SourcesDirectory)/artifacts/TestResults/**/*.xml'
            mergeTestResults: true
            searchFolder: $(system.defaultworkingdirectory)
            testRunTitle: XHarness unit tests - $(Agent.JobName)
          condition: succeededOrFailed()

# E2E tests

- stage: E2E
  displayName: E2E
  dependsOn: Build_OSX
  jobs:
  - template: /eng/common/core-templates/job/helix-job-monitor.yml

  - template: eng/e2e-test.yml
    parameters:
      name: E2E_iOS_Devices
      displayName: Apple - iOS devices
      testProject: $(Build.SourcesDirectory)/tests/integration-tests/Apple/Device.iOS.Tests.proj

  - template: eng/e2e-test.yml
    parameters:
      name: E2E_tvOS_Devices
      displayName: Apple - tvOS devices
      testProject: $(Build.SourcesDirectory)/tests/integration-tests/Apple/Device.tvOS.Tests.proj

  - template: eng/e2e-test.yml
    parameters:
      name: E2E_Apple_Device_Commands
      displayName: Apple - Device Commands
      testProject: $(Build.SourcesDirectory)/tests/integration-tests/Apple/Device.Commands.Tests.proj
