//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.XHarness.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.XHarness.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to application bundle.
        /// </summary>
        public static string Arg_AppPath_Description {
            get {
                return ResourceManager.GetString("Arg_AppPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the device/simulator to use.
        /// </summary>
        public static string Arg_DeviceName_Description {
            get {
                return ResourceManager.GetString("Arg_DeviceName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this message and exit.
        /// </summary>
        public static string Arg_Help_Description {
            get {
                return ResourceManager.GetString("Arg_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout in seconds for the app to start. Default is {0} seconds.
        /// </summary>
        public static string Arg_LaunchTimeout_Description {
            get {
                return ResourceManager.GetString("Arg_LaunchTimeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to which the simulator/device output will be saved.
        /// </summary>
        public static string Arg_OutputDirectory_Description {
            get {
                return ResourceManager.GetString("Arg_OutputDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test target (device/simulator and OS).
        /// </summary>
        public static string Arg_Target_Description {
            get {
                return ResourceManager.GetString("Arg_Target_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout in seconds. Default is {0} seconds.
        /// </summary>
        public static string Arg_Timeout_Description {
            get {
                return ResourceManager.GetString("Arg_Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging verbosity level.
        /// </summary>
        public static string Arg_Verbosity_Description {
            get {
                return ResourceManager.GetString("Arg_Verbosity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke bundled adb with given arguments.
        /// </summary>
        public static string Android_Adb_Description {
            get {
                return ResourceManager.GetString("Android_Adb_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ID of the device compatible with a given .apk / architecture.
        /// </summary>
        public static string Android_Device_Description {
            get {
                return ResourceManager.GetString("Android_Device_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install an .apk on an Android device without running it.
        /// </summary>
        public static string Android_Install_Description {
            get {
                return ResourceManager.GetString("Android_Install_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests using an already installed .apk on an Android device.
        /// </summary>
        public static string Android_Run_Description {
            get {
                return ResourceManager.GetString("Android_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print information about the current machine, such as host machine info and device status.
        /// </summary>
        public static string Android_State_Description {
            get {
                return ResourceManager.GetString("Android_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes test .apk on an Android device, waits up to a given timeout, then copies files off the device and uninstalls the test app.
        /// </summary>
        public static string Android_Test_Description {
            get {
                return ResourceManager.GetString("Android_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall an .apk from an Android device.
        /// </summary>
        public static string Android_Uninstall_Description {
            get {
                return ResourceManager.GetString("Android_Uninstall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a test folder to an Android device without running it.
        /// </summary>
        public static string AndroidHeadless_Install_Description {
            get {
                return ResourceManager.GetString("AndroidHeadless_Install_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests using an already installed executable on an Android device.
        /// </summary>
        public static string AndroidHeadless_Run_Description {
            get {
                return ResourceManager.GetString("AndroidHeadless_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes test executable on an Android device, waits up to a given timeout, then copies files off the device and uninstalls the test app.
        /// </summary>
        public static string AndroidHeadless_Test_Description {
            get {
                return ResourceManager.GetString("AndroidHeadless_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall a test folder from an Android device.
        /// </summary>
        public static string AndroidHeadless_Uninstall_Description {
            get {
                return ResourceManager.GetString("AndroidHeadless_Uninstall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds the UDID of a device/simulator for given target.
        /// </summary>
        public static string Apple_Device_Description {
            get {
                return ResourceManager.GetString("Apple_Device_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs a given iOS/tvOS/watchOS/xrOS/MacCatalyst application bundle in a target device/simulator.
        /// </summary>
        public static string Apple_Install_Description {
            get {
                return ResourceManager.GetString("Apple_Install_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs an already installed iOS/tvOS/watchOS/xrOS/MacCatalyst test application containing a TestRunner in a target device/simulator and tries to detect the exit code..
        /// </summary>
        public static string Apple_JustRun_Description {
            get {
                return ResourceManager.GetString("Apple_JustRun_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs an already installed iOS/tvOS/watchOS/xrOS/MacCatalyst test application containing a TestRunner in a target device/simulator..
        /// </summary>
        public static string Apple_JustTest_Description {
            get {
                return ResourceManager.GetString("Apple_JustTest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke bundled mlaunch with given arguments.
        /// </summary>
        public static string Apple_Mlaunch_Description {
            get {
                return ResourceManager.GetString("Apple_Mlaunch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs, runs and uninstalls a given iOS/tvOS/watchOS/xrOS/MacCatalyst application bundle in a target device/simulator and tries to detect the exit code..
        /// </summary>
        public static string Apple_Run_Description {
            get {
                return ResourceManager.GetString("Apple_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds whether given simulators are installed and outputs list of missing ones (returns 0 when none missing).
        /// </summary>
        public static string Apple_Simulators_Find_Description {
            get {
                return ResourceManager.GetString("Apple_Simulators_Find_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs given simulators.
        /// </summary>
        public static string Apple_Simulators_Install_Description {
            get {
                return ResourceManager.GetString("Apple_Simulators_Install_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists available simulators.
        /// </summary>
        public static string Apple_Simulators_List_Description {
            get {
                return ResourceManager.GetString("Apple_Simulators_List_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets given iOS/tvOS simulator (wipes it clean).
        /// </summary>
        public static string Apple_Simulators_Reset_Description {
            get {
                return ResourceManager.GetString("Apple_Simulators_Reset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print information about the current machine, such as host machine info and device status.
        /// </summary>
        public static string Apple_State_Description {
            get {
                return ResourceManager.GetString("Apple_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs, runs and uninstalls a given iOS/tvOS/watchOS/xrOS/MacCatalyst test application bundle containing TestRunner in a target device/simulator..
        /// </summary>
        public static string Apple_Test_Description {
            get {
                return ResourceManager.GetString("Apple_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apple test --app=... --output-directory=... --target=... [OPTIONS] [-- [RUNTIME ARGUMENTS]].
        /// </summary>
        public static string Apple_Test_Usage {
            get {
                return ResourceManager.GetString("Apple_Test_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalls a given iOS/tvOS/watchOS/xrOS/MacCatalyst application bundle from a target device/simulator.
        /// </summary>
        public static string Apple_Uninstall_Description {
            get {
                return ResourceManager.GetString("Apple_Uninstall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty value supplied to {0}.
        /// </summary>
        public static string Error_EmptyValue {
            get {
                return ResourceManager.GetString("Error_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value '{0}' supplied for {1}. Valid values are:{2}.
        /// </summary>
        public static string Error_InvalidValue {
            get {
                return ResourceManager.GetString("Error_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be an integer.
        /// </summary>
        public static string Error_MustBeInteger {
            get {
                return ResourceManager.GetString("Error_MustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be an integer - a number of seconds, or a timespan (00:30:00).
        /// </summary>
        public static string Error_MustBeIntegerOrTimespan {
            get {
                return ResourceManager.GetString("Error_MustBeIntegerOrTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument {0} was not supplied.
        /// </summary>
        public static string Error_RequiredArgumentMissing {
            get {
                return ResourceManager.GetString("Error_RequiredArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected failure argument: {0}.
        /// </summary>
        public static string Error_UnexpectedFailure {
            get {
                return ResourceManager.GetString("Error_UnexpectedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown arguments: {0}.
        /// </summary>
        public static string Error_UnknownArguments {
            get {
                return ResourceManager.GetString("Error_UnknownArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported sub-commands:.
        /// </summary>
        public static string Help_AllSupportedSubCommands {
            get {
                return ResourceManager.GetString("Help_AllSupportedSubCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The '{0}' command is not available on non-OSX platforms!.
        /// </summary>
        public static string Help_CommandNotAvailableOnNonOSX {
            get {
                return ResourceManager.GetString("Help_CommandNotAvailableOnNonOSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available for command '{0}'. Allowed commands are 'apple', 'wasm', 'wasi' and 'android'.
        /// </summary>
        public static string Help_NoHelpAvailableForCommand {
            get {
                return ResourceManager.GetString("Help_NoHelpAvailableForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run 'xharness {0} {{command}} --help' for more details.
        /// </summary>
        public static string Help_RunForMoreDetails {
            get {
                return ResourceManager.GetString("Help_RunForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown sub-command '{0}'..
        /// </summary>
        public static string Help_UnknownSubCommand {
            get {
                return ResourceManager.GetString("Help_UnknownSubCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: {0}.
        /// </summary>
        public static string Help_Usage {
            get {
                return ResourceManager.GetString("Help_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] XHarness command issued: {1}.
        /// </summary>
        public static string Log_XHarnessCommandIssued {
            get {
                return ResourceManager.GetString("Log_XHarnessCommandIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XHarness exit code: {0}{1}.
        /// </summary>
        public static string Log_XHarnessExitCode {
            get {
                return ResourceManager.GetString("Log_XHarnessExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes tests on WASI using a selected engine.
        /// </summary>
        public static string Wasi_Test_Description {
            get {
                return ResourceManager.GetString("Wasi_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes tests on WASM using a browser.
        /// </summary>
        public static string Wasm_TestBrowser_Description {
            get {
                return ResourceManager.GetString("Wasm_TestBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes tests on WASM using a selected JavaScript engine.
        /// </summary>
        public static string Wasm_Test_Description {
            get {
                return ResourceManager.GetString("Wasm_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a webserver.
        /// </summary>
        public static string Wasm_WebServer_Description {
            get {
                return ResourceManager.GetString("Wasm_WebServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save diagnostics data to '{0}': {1}.
        /// </summary>
        public static string Common_DiagnosticsDataSaveFailed {
            get {
                return ResourceManager.GetString("Common_DiagnosticsDataSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbolicator given.
        /// </summary>
        public static string Common_NoSymbolicatorGiven {
            get {
                return ResourceManager.GetString("Common_NoSymbolicatorGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolicator '{0}' is not of WasmSymbolicatorBase type..
        /// </summary>
        public static string Common_InvalidSymbolicatorType {
            get {
                return ResourceManager.GetString("Common_InvalidSymbolicatorType", resourceCulture);
            }
        }
    }
}